### ISSUE TITLE
System.MissingMethodException with collectors on .NET 5

### ISSUE THREAD

**Issue by fredrikcarlbom** [coverlet-coverage/coverlet#1047] opened 2021-01-14 10:18 UTC
This is the first time trying coverlet but I cannot get it to work with either version 3.0.0 nor 1.3.0

This is my minimal test repository: https://github.com/fredrikcarlbom/coverlet/tree/main

This is the test project file from the repo - lib1.tests.csproj:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>

    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.8.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
```

I build using build.sh:
```bash
#!/bin/bash

mkdir out
dotnet publish ./lib1.tests -c Release -o out
cd out
dotnet test lib1.tests.dll --collect:"XPlat Code Coverage"
```

And this is the complete output:

```
/mnt/c/Work/coverlet$ ./build.sh
mkdir: cannot create directory ‘out’: File exists
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /mnt/c/Work/coverlet/lib1.tests/lib1.tests.csproj (in 351 ms).
  lib1.tests -> /mnt/c/Work/coverlet/lib1.tests/bin/Release/net5.0/lib1.tests.dll
  lib1.tests -> /mnt/c/Work/coverlet/out/
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
'.ta collection : Unable to find a datacollector with friendly name 'XPlat Code Coverage
'ata collection : Could not find data collector 'XPlat Code Coverage
Testhost process exited with error: Unhandled exception. System.MissingMethodException: Method not found: 'Boolean Microsoft.VisualStudio.TestPlatform.CoreUtilities.Helpers.CommandLineArgumentsHelper.TryGetIntArgFromDict(System.Collections.Generic.IDictionary`2<System.String,System.String>, System.String, Int32 ByRef)'.
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.SetParentProcessExitCallback(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
. Please check the diagnostic logs for more information.

Test Run Aborted.
```

I have the same behavior when running in powershell and WSL.

**Comment by Malivil** [comment] 2021-01-14 14:25
Looks to be a duplicate of #1042 where they are looking for a same reproduction project

**Comment by fredrikcarlbom** [comment] 2021-01-14 14:28
@Malivil I get the same error if I downgrade to 1.3.0, therefore I assumed it would be two different issues.

**Comment by Malivil** [comment] 2021-01-14 15:26
Sorry, I was focusing on that exception message.

**Comment by petli** [comment] 2021-01-14 16:22
These error messages look suspicious:

    '.ta collection : Unable to find a datacollector with friendly name 'XPlat Code Coverage
    'ata collection : Could not find data collector 'XPlat Code Coverage

They should look like this:

    Data collection : Unable to find a datacollector with friendly name 'XPlat Code Coverage'.
    Data collection : Could not find data collector 'XPlat Code Coverage'

That the end of them has been moved to the start of the line makes me think there's a carriage return `\r` hiding at the end of this line in the script:

    dotnet test lib1.tests.dll --collect:"XPlat Code Coverage"

Have a look at your script to check that it doesn't DOS line endings (i.e. CRLF or `\r\n`), and if it does convert it to UNIX line endings (just LF/`\n`). Bash doesn't understand DOS line endings.

**Comment by MarcoRossignoli** [comment] 2021-01-14 16:56
Collectors doesn't work with dll with `test` you need to publish first and use `vstest` as explained in the guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-integration-with-vstest-aka-visual-studio-test-platform

```
dotnet publish
...
  ... -> C:\project\bin\Debug\netcoreapp3.0\testdll.dll
  ... -> C:\project\bin\Debug\netcoreapp3.0\publish\
...
dotnet vstest C:\project\bin\Debug\netcoreapp3.0\publish\testdll.dll --collect:"XPlat Code Coverage"
```

**Comment by petli** [comment] 2021-01-14 18:22
Try @MarcoRossignoli 's suggestion first, the error messages I saw may not be the root cause.

**Comment by fredrikcarlbom** [comment] 2021-01-14 19:02
> 
> 
> Collectors doesn't work with dll with `test` you need to publish first and use `vstest` as explained in the guide https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/VSTestIntegration.md#coverlet-integration-with-vstest-aka-visual-studio-test-platform
> 
> ```
> dotnet publish
> ...
>   ... -> C:\project\bin\Debug\netcoreapp3.0\testdll.dll
>   ... -> C:\project\bin\Debug\netcoreapp3.0\publish\
> ...
> dotnet vstest C:\project\bin\Debug\netcoreapp3.0\publish\testdll.dll --collect:"XPlat Code Coverage"
> ```

I had read that page but the following fooled me, is it supposed to be `dotnet vstest` or what am I missing?

>With correct reference in place you can run coverage through default dotnet test CLI verbs:
>
>`dotnet test --collect:"XPlat Code Coverage"`

**Comment by MarcoRossignoli** [comment] 2021-01-14 19:55
Of you pass test library you need to publish before and use `vstest` if you run against sln/csproj you can use `test` and void to publish.

**Comment by fredrikcarlbom** [comment] 2021-01-15 11:27
I changed the build to:
```bash
#!/bin/bash

dotnet publish ./lib1.tests -c Release -o out
pushd out
dotnet vstest lib1.tests.dll --collect:"XPlat Code Coverage"
popd
```

And get the following:
```
/mnt/c/Work/coverlet$ ./build.sh
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /mnt/c/Work/coverlet/lib1/lib1.csproj (in 106 ms).
  Restored /mnt/c/Work/coverlet/lib1.tests/lib1.tests.csproj (in 299 ms).
  lib1 -> /mnt/c/Work/coverlet/lib1/bin/Release/net5.0/lib1.dll
  lib1.tests -> /mnt/c/Work/coverlet/lib1.tests/bin/Release/net5.0/lib1.tests.dll
  lib1.tests -> /mnt/c/Work/coverlet/out/
/mnt/c/Work/coverlet/out /mnt/c/Work/coverlet
Microsoft (R) Test Execution Command Line Tool Version 16.8.3
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: Unhandled exception. System.MissingMethodException: Method not found: 'Boolean Microsoft.VisualStudio.TestPlatform.CoreUtilities.Helpers.CommandLineArgumentsHelper.TryGetIntArgFromDict(System.Collections.Generic.IDictionary`2<System.String,System.String>, System.String, Int32 ByRef)'.
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.SetParentProcessExitCallback(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.DefaultEngineInvoker.Invoke(IDictionary`2 argsDictionary)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Run(String[] args)
   at Microsoft.VisualStudio.TestPlatform.TestHost.Program.Main(String[] args)
. Please check the diagnostic logs for more information.

Attachments:
  /mnt/c/Work/coverlet/out/TestResults/31084328-058e-403c-8d55-3255951e325c/coverage.cobertura.xml
Test Run Aborted.
/mnt/c/Work/coverlet
```

I can build and test `Documentation/Examples/VSTest/HelloWorld/XUnitTestProject1` but that includes all the files in the root folder, if I copy the HelloWorld folder outside of the coverlet root folder, I can no longer test using the published version, only the project directly.
There are so many global files in the root folder, can you point me in the right direction to which references/settings that are needed for vstest of published projects?

**Comment by MarcoRossignoli** [comment] 2021-01-15 13:27
your command `dotnet vstest lib1.tests.dll --collect:"XPlat Code Coverage"` it's correct, now the problem is another one and we need to understand why on 5 it's failing with that missing method.

**Comment by fredrikcarlbom** [comment] 2021-01-15 13:34
> 
> 
> your command `dotnet vstest lib1.tests.dll --collect:"XPlat Code Coverage"` it's correct, now the problem is another one and we need to understand why on 5 it's failing with that missing method.

Is this good enough or should I edit the original issue?

**Comment by MarcoRossignoli** [comment] 2021-01-15 13:37
I'm going to close this because it's a dup follow this one https://github.com/coverlet-coverage/coverlet/issues/1042

**Comment by fredrikcarlbom** [comment] 2021-01-15 13:38
Great, thanks for all your help!

**Closed by MarcoRossignoli** 2021-01-15 13:37 UTC
Labels: as-designed
