### ISSUE TITLE
Coverage went down after Upgrade to version 3.0.0 

### ISSUE THREAD

**Issue by edenjp** [coverlet-coverage/coverlet#1048] opened 2021-01-14 11:45 UTC
I was very happy when I saw a new version with an update I needed. But after Upgrade to version 3.0.0, the code coverage percent went down and a lot of lines that before was been read, are not anymore.

I am downgrading the version until I figure it out what happened. Does anybody had the same problem or have ideas of what happened and how can I fixed?

**Comment by Malivil** [comment] 2021-01-14 12:30
Duplicate of #1043, fixed in nightly and next release

**Closed** 2021-01-14 16:54 UTC
Labels: duplicate
