### ISSUE TITLE
Question: branch coverage - information which branches were covered?

### ISSUE THREAD

**Issue by pkruk2** [coverlet-coverage/coverlet#1070] opened 2021-01-26 12:16 UTC
Hi,

is it possible to know which branches were covered? 

I guess that would matter mainly (only?) for switch statements - to know which switch cases were reached.
For other statements with only 2 branches (if/for) I suppose you'll know based for line coverage information.
But for switch statement there is no line coverage for case labels...

**Comment by MarcoRossignoli** [comment] 2021-01-27 07:33
The question is not clear do you mean a report like this https://github.com/coverlet-coverage/coverlet/pull/1006#issuecomment-739503270?

**Comment by pkruk2** [comment] 2021-02-02 13:09
Hello, sorry for delay.

What I mean: for example if I have following switch (a simplified example):

```switch (x) {
   case 1:
   case 2:
       break;
}```

I might get following information:
* "break" line was covered
* 12 out of 20 branches were covered (nor real values for this simplified code but show the problem)

So I will know looking at the line coverage that switch was executed with value 1 or value 2 (or both), but I will not know which one.
This can be useful for example if I wanted to make sure all possible switch case labels are tested/covered.

**Comment by MarcoRossignoli** [comment] 2021-02-08 08:14
I think that in this case the issue is the compiler optimization on IL generation, take a look at generated IL 

![image](https://user-images.githubusercontent.com/7894084/107192429-e2502180-69ed-11eb-9d49-9d356a270290.png)
![image](https://user-images.githubusercontent.com/7894084/107192492-f85de200-69ed-11eb-995b-366918542adc.png)

The generated branches are:
```json
{
  "Example.Core.dll": {
    "C:\\git\\playground\\coverlet\\Example\\Example.Core\\Switch.cs": {
      "Example.Core.Switch": {
        "System.Void Example.Core.Switch::Test(System.Int32)": {
          "Lines": {
            "10": 1,
            "11": 1,
            "15": 1,
            "17": 1
          },
          "Branches": [
            {
              "Line": 11,
              "Offset": 9,
              "EndOffset": 15,
              "Path": 0,
              "Ordinal": 0,
              "Hits": 1
            },
            {
              "Line": 11,
              "Offset": 9,
              "EndOffset": 15,
              "Path": 1,
              "Ordinal": 1,
              "Hits": 1
            }
          ]
        }
      }
    }
  }
}
```

**Comment by MarcoRossignoli** [comment] 2021-02-21 14:08
Closed as designed, seems a compiler optimization. Feel free to reopen if needed.

**Closed by MarcoRossignoli** 2021-02-21 14:08 UTC
Labels: as-designed, question
