### ISSUE TITLE
How to generate report in .coverage format

### ISSUE THREAD

**Issue by qinl-li** [coverlet-coverage/coverlet#1440] opened 2023-01-26 21:38 UTC
Hi, 

I am working on adding a coverage status check for our pull request. 
According to [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/test/codecoverage-for-pullrequests?source=recommendations&view=azure-devops#which-coverage-tools-and-result-formats-can-be-used-for-validating-code-coverage-in-pull-requests), it only access .coverage file to make the check shows up.  

Here is the command line we are using for running the test, but it only generated HTML format. I tried to pass different format value and still can't get .coverage file. Is there any limitation on Linux container? 

**- task: DotNetCoreCLI@2
          displayName: 'Test'
          inputs:
            command: test
            publishTestResults: false # cannot publish test result due to policy restriction, disable it here and use PublishTestResults@2 to publish
            projects: 'src/**/*.Tests.csproj'
            arguments: '--no-restore --logger trx -c $(BuildConfiguration) /p:BuildMetadata=$(Build.BuildNumber) --settings $(Build.SourcesDirectory)/src/Tests.runsettings --filter "Category=Unit|Category=Integration" -m:1 --results-directory $(Build.SourcesDirectory)/src/unit-test/test-result/ /p:CollectCoverage=true  /p:CoverletOutput=$(Build.SourcesDirectory)/src/unit-test/coverage-result/ /p:MergeWith=$(Build.SourcesDirectory)/src/unit-test/coverage-result/coverlet.json /p:CoverletOutputFormat="json%2ccobertura"**'

**Comment by daveMueller** [comment] 2023-01-26 23:03
I think the link you posted refers to Visual Studio coverage. AFAIK `coverlet` doesn't have support for this format but I also could be wrong. Nevertheless you could try it with [dotnet-coverage](https://learn.microsoft.com/en-us/dotnet/core/additional-tools/dotnet-coverage).

**Comment by qinl-li** [comment] 2023-01-27 22:48
Thanks!

**Comment by daveMueller** [comment] 2023-04-10 20:51
I'm closing this as it is a duplicate of #1445 and progress will be tracked there. Feel free to reopen.

**Closed by daveMueller** 2023-04-10 20:51 UTC
