### ISSUE TITLE
Misreport of uncovered branch on first line of iterators

### ISSUE THREAD

**Issue by kaosborn** [coverlet-coverage/coverlet#729] opened 2020-02-13 23:20 UTC
Below is an example from a minimal program that reproduces an issue where Coverlet misreports an uncovered branch on the first line of iterators.

https://github.com/kaosborn/TestBench/blob/8ff5350eb16069523ba73b4521a5490371379101/Sequences/Numbers.cs#L7-L12

And the test case:

https://github.com/kaosborn/TestBench/blob/8ff5350eb16069523ba73b4521a5490371379101/Test/TestSequences.cs#L9-L20

In this example, Coverlet reports the first line as "1 of 2 branches are covered". Looking at the disassembled IL, possibly due to branching in the generic `GetEnumerator()` method?

![IteratorCoverage1](https://user-images.githubusercontent.com/27261136/74398952-058dc400-4dce-11ea-8a49-7cc5e3942309.png)

And here is the build:

https://github.com/kaosborn/TestBench/blob/8ff5350eb16069523ba73b4521a5490371379101/.github/workflows/Build.yml#L14-L23

**Comment by MarcoRossignoli** [comment] 2020-02-14 09:06
Which version/driver type of coverlet are you using?

**Comment by MarcoRossignoli** [comment] 2020-02-14 09:08
@matteoerigozzi what do you think?IIRW there was an issue on enumerator fixed on master...

**Comment by kaosborn** [comment] 2020-02-14 10:16
> 
> 
> ~Which version/driver type of coverlet are you using?~
> Never mind found https://github.com/kaosborn/TestBench, is this project right?

coverlet.collector v1.2.0; coverlet.msbuild v2.8.0; Microsoft.NET.Test.Sdk 16.4.0; MSTest.TestAdapter v2.0.0; MSTest.TestFramework v2.0.0

Right, the trivial project referenced above. This issue also dings the stats on two of my other "real" projects.

**Comment by MarcoRossignoli** [comment] 2020-02-14 10:22
Remember if you're using collector you need to reference updated version of `Microsoft.NET.Test.Sdk` https://github.com/tonerdo/coverlet/blob/master/Documentation/VSTestIntegration.md

BTW is not related to issue is reported.

**Comment by MarcoRossignoli** [comment] 2020-02-18 19:49
Confirm the bug. cc: @matteoerigozzi

**Comment by Bertk** [comment] 2024-01-22 12:49
The issue might be out-dated because new releases are available.

Please reopen the issue if the bug still exists and can be reproduced with latest preview from [coverlet nightly build](https://dev.azure.com/tonerdo/coverlet/_artifacts/feed/coverlet-nightly).

see [Consume nightly build](https://github.com/coverlet-coverage/coverlet/blob/9295fca754531d6badd0185d0709d41a6eeddd5f/Documentation/ConsumeNightlyBuild.md)

**Closed by Bertk** 2024-01-22 12:49 UTC
Labels: bug, tenet-coverage
