### ISSUE TITLE
Coverlet throws BadImageFormatException 

### ISSUE THREAD

**Issue by AdityaKSemwal** [coverlet-coverage/coverlet#1612] opened 2024-02-09 13:36 UTC
Hi,

I am trying to run Coverlet but it throws the following error for every dll
_BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable to check if the module has got local source._
![image](https://github.com/coverlet-coverage/coverlet/assets/148043294/dc09c829-32db-4044-976f-5fa692b1430e)

I have sets of e-2-e tests that can be run only through executable application.
here is the command I am following 
_coverlet D:\d\Source\myProject\bin\Debug --target "C:\Program Files\myProject.exe" --output "D:\coverlet.xml" --format opencover_ 

I can open exe and run tests but I am not getting any code coverage.
Any Idea how to fix this issue?
I m using coverlet.console on .net framework project

**Comment by Bertk** [comment] 2024-02-11 11:31
Please read the [documentation](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage) and use the proposed parameters.

`coverlet /path/to/test-assembly.dll --target "dotnet" --targetargs "test /path/to/test-project --no-build"`

**Comment by daveMueller** [comment] 2024-02-11 20:57
I think you are doing everything correct as described [here](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage-for-integration-tests-and-end-to-end-tests) for e-2-e tests. But I must admit I haven't used coverlet for integration tests in years. 
Without having something to debug it is really hard to say why this exception is being thrown. 
Which version of coverlet are you using and are you working with full or portable pdbs?  Maybe this issue https://github.com/coverlet-coverage/coverlet/issues/1348 is related and you can try out the solution there.
Nevertheless a repro would really help to analyze this.

**Comment by AdityaKSemwal** [comment] 2024-02-12 13:44
I did more investigation and understood that BadImageFormatException is not an issue.
It is also thrown for normal unit tests but I get coverage reports.
The only problem I am facing is Coverlet is not gathering live coverage after a tool startup the executable.

most probably it is caused by an error 
 [0212/191135.687:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
DevTools listening on ws://127.0.0.1:8088/devtools/browser/210e2f33-0b05-4860-8927-54e36a43910e

**Comment by AdityaKSemwal** [comment] 2024-02-14 14:19
@daveMueller  thanks for your response.
But the link you gave is not my issue.
I managed to make it work for normal unit tests as i was missing nunit test adapter. but still struggling with e-2-e tests.
Everything is fine but it doesn't have code coverage

**Comment by daveMueller** [comment] 2024-02-14 22:43
The link I posted has nothing to do with normal unit tests ([Code Coverage for integration tests and end-to-end tests](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/GlobalTool.md#code-coverage-for-integration-tests-and-end-to-end-tests)). I can remember that I have done this at least once for e-2-e tests with Selenium. If you can provide a simple repro with the tools you are using, I could give it a try myself.

**Comment by AdityaKSemwal** [comment] 2024-02-15 07:11
I don't have repro, I am using Autodesk Revit.exe as a target.
and I have an add-in that runs tests through this application.

so here is the scenario 
1. open revit.exe 
2. run the addin
3. Select the test dll
4. tests are running through testrunner(class from nunit.core)

**Comment by daveMueller** [comment] 2024-02-15 22:52
OK I see, nothing I can reproduce by myself. Can you post a detailed output here? Maybe we can find some hints there. Just set the verbosity level to detailed. ([troubleshoot](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Troubleshooting.md#coverlet-global-tool))

**Comment by daveMueller** [comment] 2024-02-17 23:18
Sorry can't really identify what the problem is. Like you already mentioned, this looks a bit suspicious.
```
[0216/123237.157:ERROR:gpu_process_transport_factory.cc(1029)] Lost UI shared context.
DevTools listening on ws://127.0.0.1:8088/devtools/browser/f6aefc4a-7038-4e4b-b810-df0251bf48a1
```
As also mentioned in the documentation, coverlet is currently a bit limited for e-2-e tests and relies on a graceful
process shutdown. There is some more information about this in those two issues #1079, #781. You probably can try out the coverage tool of MS that has a bit more advanced possibilities for e-2-e. https://github.com/coverlet-coverage/coverlet/issues/781#issuecomment-1340707747

Any other ideas @Bertk @MarcoRossignoli?

**Comment by Bertk** [comment] 2024-02-18 06:03
@daveMueller I never tried to generate source code coverage metrics for e2e tests. We used a test concept which defined a test pyramid and source code coverage was mandatory for unit test and unit integration tests.

test pyramid was similar to this.
<img width="1366" alt="image" src="https://github.com/coverlet-coverage/coverlet/assets/2315215/4a685e65-d34b-442d-b14f-3819578673af">

**Comment by lineburg** [comment] 2024-04-24 21:44
Castle.Core.dll might be causing your problem.
I got this error when a project that was not... suddenly WAS referencing it.
It is not necessarily the fact that you reference Castle.Core.dll but might be the wrong "bitness".
"BadImageFormatException is usually due to bitness. One project is 64 bit and the the other is 32 bit. Make sure both project target the same bitness x86 or 64."

**Comment by xPaw** [comment] 2024-07-27 17:02
Seeing the same issue while trying to setup coverlet.msbuild.

Repro project: https://github.com/SteamRE/SteamKit/blob/master/SteamKit2/Tests/Tests.csproj

Install `coverlet.msbuild` and then try to test it: `dotnet test SteamKit2/Tests/Tests.csproj /p:CollectCoverage=true`

**Comment by Bertk** [comment] 2024-08-20 09:16
@xPaw Thank you for the repo. I did small modifications (AnyCPU) and removed some files.

This warning message occurred
> C:\Users\XXX\.nuget\packages\coverlet.msbuild\6.0.2\build\coverlet.msbuild.targets(39,5): warning : [coverlet] BadImageFormatException during MetadataReaderProvider.FromPortablePdbStream in InstrumentationHelper.PortablePdbHasLocalSource, unable t
o check if module has got local source. [C:\GitHub\coverlet-issue-1612\SteamKit2\Tests\Tests.csproj]

I noticed the output folder did not have any PDB files and updated the configuration for **embedded** debug symbols (SteamKit2, SteamLanguageParser)
<img width="323" alt="image" src="https://github.com/user-attachments/assets/51b482f6-4c44-40d0-88c8-b5353046aadb">

 
<img width="798" alt="image" src="https://github.com/user-attachments/assets/462c9adc-4ede-4355-a56e-3ffe6f424d33">

Not sure whether this helps.,

**Comment by xPaw** [comment] 2024-08-20 09:27
SteamKit2 does output full pdb for a debug build, and SteamLanguageParser is not covered by tests.

```
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
```

Not sure what you changed with anycpu, it's already anycpu.

**Comment by Bertk** [comment] 2024-08-20 11:01
@xPaw I did not analyze the dependencies but removed not necessary files for my tests. I prefer embedded symbols for and did not use portable at all.

This is also something special in SteamKit2 project file:
https://github.com/SteamRE/SteamKit/blob/975e9334dc248dcac2981cfe2d7d84d37113ef34/SteamKit2/SteamKit2/SteamKit2.csproj#L23

**Comment by xPaw** [comment] 2024-08-20 11:34
That line only affects packing the pdb into nuget, shouldn't affect tests.

**Comment by Bertk** [comment] 2024-08-21 08:25
> That line only affects packing the pdb into nuget, shouldn't affect tests.

I do not understand the condition for this setting.

Please confirm your issue is resolved and the `BadImageFormatException` does not occur ansmore.

**Comment by xPaw** [comment] 2024-08-21 08:32
My issue seems to be resolved by changing debug type from `full` to `portable`. So the bug seems that coverlet is unable to read the full debug symbols format?

**Comment by Bertk** [comment] 2024-08-22 08:11
I am not sure whether this is a regression or bug (see #1003, #1100).

>The Portable PDB format was introduced in .NET Core, and it's used by default when targeting .NET. When targeting .NET Framework, you can enable portable PDB symbols by specifying <DebugType>portable</DebugType> in your project file. The portable PDB format is based on ECMA-335 metadata format. For more information, see [Portable PDB v1.0: Format Specification](https://github.com/dotnet/runtime/blob/main/docs/design/specs/PortablePdb-Metadata.md). Diagnostic tools can use the [System.Reflection.Metadata](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadata) library to read portable PDB files (for an example, see [System.Reflection.Metadata.Document](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.metadata.document)). 

> Windows PDBs can only be written or read on Windows. Using Windows PDBs for managed code is obsolete and is only needed for legacy tools. It is recommended that you use portable PDBs instead of Windows PDBs, as some newer compiler features are implemented only for portable PDBs.

> The difference is that the "full" type emits a classic windows PDB symbol file which is complex and poorly documented.

Maybe a hint in coverlet documentation would be helpful.

**Closed** 2024-09-11 02:43 UTC
Labels: question

**Comment by Gua-naiko-che** [comment] 2024-09-16 08:08
> My issue seems to be resolved by changing debug type from `full` to `portable`. So the bug seems that coverlet is unable to read the full debug symbols format?

This worked for me.

**Comment by Bertk** [comment] 2024-09-16 08:50
Thank you for the feedback. 

coverlet was created for .NET core and supports .NET framework but there is no plan to support _DebugType_ **full** (windows only)
