### ISSUE TITLE
Code coverage results are empty for the assembly paths that contain *DataCollector* keyword.

### ISSUE THREAD

**Issue by levangode** [coverlet-coverage/coverlet#1386] opened 2022-09-29 17:51 UTC
Hi,

Using version 3.1.2 but faced the same issue trying older versions.
Both my test project and main project under test are located on the file paths which contain *DataCollector* keyword on it. On top of that, the assembly names (.dlls) under test also have the keyword in the name. i.e. MyDataCollectorApplication

The generated .coverage result file is empty. As soon as I rename the paths & dll names to something other than what contains *DataCollector*, i.e. MyDatColApplication, then it starts generating the coverage results correctly.

I'm assuming this is somehow colliding with coverlet DataCollector entity and the way it is being looked up on the path (??)

Is there any workaround on this? I tried using the custom runsettings, but doesn't seem to be helping

**Comment by daveMueller** [comment] 2022-12-25 01:17
Thanks, I try to clarify this with the `vstest` team and hope we find a solution for that. Here is the link to the issue in the `vstest` repo [https://github.com/microsoft/vstest/issues/4226](https://github.com/microsoft/vstest/issues/4226) which also contains a repro.

**Comment by daveMueller** [comment] 2023-01-07 22:34
@levangode unfortunately there is nothing we can do because `vstest` has some "dynamic loading using file naming convention" by [design](https://github.com/Microsoft/vstest-docs/blob/main/docs/extensions/datacollector.md#extend-datacollector) which interferes with coverlets' coverage process. If you really need an assembly that ends with the name `*collector.dll` to be covered, you could consider to use `coverlet.msbuild` or `coverlet.console`.

I'll close this as it is by design of `vstest`. Feel free to reopen if needed.

**Closed by daveMueller** 2023-01-07 22:34 UTC
Labels: tracking-external-issue, with repro
