### ISSUE TITLE
0% code coverage and error in collector

### ISSUE THREAD

**Issue by tiwarishubham635** [coverlet-coverage/coverlet#1661] opened 2024-05-28 09:10 UTC
We have a C# project - https://github.com/twilio/twilio-csharp. We were earlier calculating coverage using these steps:
```
dotnet sonarscanner begin /k:"$(PROJECT_NAME)" /o:"twilio" /d:sonar.host.url=https://sonarcloud.io /d:sonar.token="${SONAR_TOKEN}"  /d:sonar.language="cs" $(SONAR_SOURCES) /d:sonar.cs.opencover.reportsPaths="test/lcov.opencover.xml" /d:"sonar.verbose=true"
# Write to a log file since the logs for build with sonar analyzer are pretty beefy and travis has a limit on the number of log lines
dotnet build Twilio.sln > buildsonar.log
dotnet test test/Twilio.Test/Twilio.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov
dotnet sonarscanner end /d:sonar.token="${SONAR_TOKEN}"
```
And were using msbuild for coverage in test.csproj like [this](https://github.com/twilio/twilio-csharp/blob/add_taskrouter_grant/test/Twilio.Test/Twilio.Test.csproj)

This was giving 0% code coverage like this:
```
Calculating coverage result...
   Generating report '/home/runner/work/twilio-csharp/twilio-csharp/test/lcov.opencover.xml'

+--------+------+--------+--------+
| Module | Line | Branch | Method |
+--------+------+--------+--------+
| Twilio | 0%   | 0%     | 0%     |
+--------+------+--------+--------+

+---------+------+--------+--------+
|         | Line | Branch | Method |
+---------+------+--------+--------+
| Total   | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
| Average | 0%   | 0%     | 0%     |
+---------+------+--------+--------+
```

Then i came across this [known issue](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md#vstest-stops-process-execution-early) and shifted to use coverlet.collectors. I am using it like this:
```
dotnet sonarscanner begin /k:"$(PROJECT_NAME)" /o:"twilio" /d:sonar.host.url=https://sonarcloud.io /d:sonar.login="${SONAR_TOKEN}"  /d:sonar.language="cs" $(SONAR_SOURCES) /d:sonar.cs.opencover.reportsPaths="test/lcov.opencover.xml"
# Write to a log file since the logs for build with sonar analyzer are pretty beefy and travis has a limit on the number of log lines
dotnet build Twilio.sln > buildsonar.log
dotnet test test/Twilio.Test/Twilio.Test.csproj --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=../lcov --collect:"XPlat Code Coverage"
dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"
```

My Test.csproj file looks like [this](https://github.com/twilio/twilio-csharp/blob/testing_dump/test/Twilio.Test/Twilio.Test.csproj) now. 

Now I am stuck with this error:
```
Error: /home/runner/work/twilio-csharp/twilio-csharp/test/Twilio.Test/Program.cs(9,20): error CS0017: Program has more than one entry point defined. Compile with /main to specify the type that contains the entry point. [/home/runner/work/twilio-csharp/twilio-csharp/test/Twilio.Test/Twilio.Test.csproj]
```

Here are the complete [logs](https://github.com/twilio/twilio-csharp/actions/runs/9266411189/job/25490573997?pr=747), if you can see.

I would like to know why is this failing and is there any fix available for msbuild as well? Thanks!

**Comment by Bertk** [comment] 2024-09-14 07:59
duplicate of #1128

>This issue was already fixed using recommended [coverlet.collector vstest integration](https://github.com/coverlet-coverage/coverlet#vstest-integration-preferred-due-to-known-issue).

>[!NOTE]  
>Use [SonarAnalyzer.CSharp](https://www.nuget.org/packages/SonarAnalyzer.CSharp) nuget package instead of  [sonarscanner ](https://www.nuget.org/packages/SonarAnalyzer.CSharp) tool. 
>The sonarqube warnings are also available in visual studio and can be configured as well using `.editorconfig`.

**Closed by Bertk** 2024-09-14 07:59 UTC
Labels: duplicate, question
