### ISSUE TITLE
Run tests only for source code changed on CI build server

### ISSUE THREAD

**Issue by prasad-1210** [coverlet-coverage/coverlet#1148] opened 2021-04-21 08:22 UTC
Hello,

I've a Dotnet core project with XUnit test cases. Its taking almost 1 hour to run tests. Is it possible to run tests by detecting changes in source code since last test or only source code changes on current branch?

Please point me to right project if this is not right place.

Thanks in advance.

**Comment by petli** [comment] 2021-04-21 10:15
In general, it is difficult to do this with any precision. Even if you have per-test code coverage and thus can see which current lines affect a specific test, you can't say for sure which tests any added lines might affect. (coverlet does not record which unit tests caused what code coverage, currently.)

I think the best you can hope for is to identify which unit test projects you need to re-run, based on which of their referenced projects have had changes. If you have a fine-grained project structure, this could reduce test time in some cases. Coverlet can't help with this approach, but perhaps you can identify that by what dotnet decides to rebuild. Something like this:

* Check out the base version of the code (the previous commit, or the base commit for the branch, depending on your CI needs)
* Build it
* Check out the new commit
* Record the current time
* Build again
* Only run the unit test projects where the DLL timestamps are newer than the recorded time before the build.

**Comment by MarcoRossignoli** [comment] 2021-05-04 19:58
This is a duplicate of https://github.com/coverlet-coverage/coverlet/issues/973

We did an offline discussion and I've suggested for now to try to fork coverlet core to try to understand if using collectors(they have start/stop test event) and coverage check on the fly(you can understand what that test touched) maybe would be possible have an "incremental" test profile and run only test that will cover updated files. But at the moment this feature is out of coverlet scope, anyway I admit that I think it could be doable.

**Comment by MarcoRossignoli** [comment] 2022-01-31 15:25
Closing because answered.

**Closed by MarcoRossignoli** 2022-01-31 15:25 UTC
Labels: duplicate
