### ISSUE TITLE
[BUG] Throw exception via method causes missing coverage

### ISSUE THREAD

**Issue by manuel-rw** [coverlet-coverage/coverlet#1652] opened 2024-04-25 11:52 UTC
**Describe the bug**
After throwing an exception via a method the method ending ``}`` is not being marked as covered.

**To Reproduce**
```csharp
    public static void EnsureNull(int? value)
    {
        if (!value.HasValue)
        {
            return;
        }
        
        CustomException.Throw(value.Value);
    }
```

https://github.com/meggima/coverlet-reproductions/pull/5

**Expected behavior**
All four lines are fully covered.

**Actual behavior**
Last line is marked as not covered:

![325590667-31c186ce-a057-4543-9252-67266e61d699](https://github.com/coverlet-coverage/coverlet/assets/30572287/2198dce5-917e-4ed4-ab9a-2a7e4e76b7da)

**Configuration (please complete the following information):**
Please provide more information on your .NET configuration:
    * Which coverlet package and version was used? ``coverlet.msbuild 3.1.2`` (also tried ``coverlet.msbuild 6.0.``)
    * Which version of .NET is the code running on? ``.net 6``
    * What OS and version, and what distro if applicable? ``Windows 10, 22H2``
    * What is the architecture (x64, x86, ARM, ARM64)? ``x64``
    * Do you know whether it is specific to that configuration? ``not specific``

**Additional context**

> :exclamation:  Please also read [Known Issues](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/KnownIssues.md)

**Comment by daveMueller** [comment] 2024-05-26 23:15
Sorry for the late response. Even tho' you marked your `Throw` method with the `DoesNotReturnAttribute`, you still need to tell coverlet that statements after this method call should be excluded from coverage ([methods-that-do-not-return](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#methods-that-do-not-return)). 

Thus you just need to add this parameter to your test execution:
```powershell
/p:DoesNotReturnAttribute="DoesNotReturnAttribute"
```

The complete call in your repro then will look like this:
```powershell
dotnet test .\CoverletReproductions.sln --no-build --no-restore --configuration release --logger:trx -v minimal /p:DoesNotReturnAttribute="DoesNotReturnAttribute" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
```
which results in a 100% coverage.

![grafik](https://github.com/coverlet-coverage/coverlet/assets/19378678/f2de1c0a-2ffe-4c62-b6ad-4cd9f7814a70)

**Comment by daveMueller** [comment] 2024-05-26 23:20
I will close this as it is as-design and a duplicate of this #1265. @manuel-rw feel free to reopen if it doesn't help.

**Closed by daveMueller** 2024-05-26 23:20 UTC
Labels: as-designed
