### ISSUE TITLE
ExcludeFromCodeCoverage not working for autogen getters and setters

### ISSUE THREAD

**Issue by pape77** [coverlet-coverage/coverlet#269] opened 2018-12-19 09:29 UTC
Noticed that when trying to apply the excludeFromCoverage attribute to getters and setters from a 
class property, they are not taken into account

```
   public class Key
    {
       [ExcludeFromCodeCoverage]
        public int Id { get; set; }

        public Guid Uuid { get; set; }

        public Guid Kid { get; set; }
    }
```

```
"/build/src/Keys.Data/Entities/Key.cs": {
      "Keys.Data.Entities.Key": {
        "System.Int32 Keys.Data.Entities.Key::get_Id()": {
          "Lines": {
            "10": 0
          },
```

This can easily be seen in action in existing tests within coverlet. In ```InstrumenterTests.cs```, in the ```TestInstrument_ClassesWithExcludeAttributeAreExcluded```
Just remove the [ExcludeFromCodeCoverage] attribute from one of the classes that this method uses in ```Samples.cs``` and add a property like this ```Id``` one. 

For example in ```Samples.cs``` change this class as follows:
```
    public class ClassExcludedByCoverletCodeCoverageAttr
    {

        public string Method(string input)
        {
            if(string.IsNullOrEmpty(input))
                throw new ArgumentException("Cannot be empty", nameof(input));

            return input;
        }

        [ExcludeFromCodeCoverage]
        public int Id { get; set; }
    }
```

Then you will that in method ```InstrumentType``` from ```Instrumenter.cs``` the attributes don't show up, because the method name is changed to ```get_Id()``` (autogenerated) and so it gets instrumented anyway.

Can we fix this somehow?

**Comment by pape77** [comment] 2018-12-19 09:36
Similar thing happens with async methods which are read like this:

```
"Keys.Data.Repositories.KeyRepository/<FindOrCreateAsync>d__6": {
        "System.Void Keys.Data.Repositories.KeyRepository/<FindOrCreateAsync>d__6::MoveNext()":
```

and then all attributes are lost when ```Instrumenter.cs``` 's method is evauluating

**Comment by SlowLogicBoy** [comment] 2018-12-19 10:35
try:
```csharp
public int MyProperty { [ExcludeFromCodeCoverage] get; [ExcludeFromCodeCoverage] set; }
```

**Comment by consultwithmike** [comment] 2018-12-19 11:00
@SlowLogicBoy that workaround does work, but I'd say we need to get something in place that iterates the Properties collection in the `Iterator` as well so that we don't have to decorate the `get` and `set`, but rather the property itself.

**Comment by pape77** [comment] 2018-12-19 15:47
Thank's for the hack @SlowLogicBoy 
Indeed @consultwithmike that's what I expected to happen. 
I'm guessing for the async things, a similar thing happens, cuz they are autogenerated with that name or something.
I looked into the ```Instrumenter.cs``` a bit, but got no clear solution for it

**Comment by MarcoRossignoli** [comment] 2019-09-28 09:10
@pape77 is this issue still here?

**Comment by StingyJack** [comment] 2021-01-13 21:54
@SlowLogicBoy @MarcoRossignoli  - this is still a problem for properties

![image](https://user-images.githubusercontent.com/15381181/104514712-b17ff680-55bf-11eb-92bb-fa824492e493.png)
![image](https://user-images.githubusercontent.com/15381181/104514736-bd6bb880-55bf-11eb-9ce5-e22ce4df9857.png)

Should this issue really be closed?

**Comment by MarcoRossignoli** [comment] 2021-01-14 07:31
This issue is old can you open new one?
Which version are you using?

**Comment by StingyJack** [comment] 2021-01-14 16:08
I was going to but found that a similar issue was opened after this and was closed as a duplicate of this.

**Comment by StingyJack** [comment] 2021-03-05 18:38
@MarcoRossignoli  As far as I can tell this was never actually fixed so closing this was not legitimate action. There is no PR or commit linked to this, just a comment for what looks like an msbuild property.

Besides like I said, other issues were opened for this same problem and were closed as duplicates of this.

**Comment by MarcoRossignoli** [comment] 2021-03-05 20:25
@StingyJack which version are you using?can you provide a repro?

**Comment by StingyJack** [comment] 2021-03-06 16:15
Both versions 1.3 and 3.0.3 (I think, will update if different)

I'm not invoking this by command line, another tool is doing the invocation that I don't have immediate control of. The repro is to put a property in a class, run coverage, see that it's uncovered, then apply the excluded attribute on the property and rerun coverage. It still shows up as uncovered.  The workaround of applying the attribute to each the get and set does work, but leaves messy code

**Comment by StingyJack** [comment] 2021-03-06 17:54
Also I dont want to skip auto properties in the first place. Any property that is not listed as covered by a unit test is something that may be unused by the code and can be removed (YAGNI), or something I should have an assertion for in a unit test (and thus make covered).   There are just some fields that are handled by an ORM or DB driver that I wouldn't unit test for, or temporary cases where the properties are needed by someone else's code that will be covering them later, but my PR needs to meet or exceed a coverage threshold to be merged.  

Usages of `[ExcludedFromCodeCoverage]`  for us need to be followed by a justification comment or it could block the changes from being merged into main. I think we may have to disable that if we cant follow the attribute with a justification comment, but I have to see if it will accept a `/**/` style comment

**Comment by MarcoRossignoli** [comment] 2021-03-06 18:16
Ok reopening for further investigation

**Closed** 2021-03-08 07:10 UTC
Labels: bug, tenet-coverage
