### ISSUE TITLE
.Net Framework/MSTest Installing coverlet.collector nuget package breaks project.

### ISSUE THREAD

**Issue by theomnislayer** [coverlet-coverage/coverlet#1126] opened 2021-03-15 07:22 UTC
Visual Studio Version: 16.9.1 (Latest as of March 15, 2021)
Coverlet.Collector Version: 3.0.3 (From nuget package manager)
Project Details: .NET Framework 4.8

Description:
Installed Coverlet.Collector 3.0.3 to .NET Framework 4.8 Project. Project is unloaded by Visual studio.
Expected:  Should be installed properly.
Actual: C:\CoverletSample\CoverletTests.csproj : error  : The expression "[System.Version]::Parse('')" cannot be evaluated. Version string portion was too short or too long.  C:\Users\omnislayer\.nuget\packages\coverlet.collector\3.0.3\build\netstandard1.0\coverlet.collector.targets

Steps to replicate: 
1. Create a new .NET Framework 4.8 project in Visual Studio (I created a new project so I can install MSTest and other test related stuff.)
2. Right click project> Manage Nuget Packages
3. Install Coverlet.Collector 3.0.3

What I tried to "fix" the problem:
1. Unload project
2. Remove References to Coverlet
![image](https://user-images.githubusercontent.com/20275306/111117101-003b1400-85a2-11eb-95f8-82c3c27d5d94.png)
![image](https://user-images.githubusercontent.com/20275306/111117126-0df09980-85a2-11eb-8904-337039907d53.png)
3. Project still has error.

The fix:
1. Created a new project and copied files. Did not install coverlet.

**Comment by MarcoRossignoli** [comment] 2021-03-16 08:39
Duplicate of https://github.com/coverlet-coverage/coverlet/issues/1119

Coverlet supports only SDK-style project https://github.com/coverlet-coverage/coverlet#quick-start 

are you on old project style?

**Closed** 2022-01-31 15:24 UTC
Labels: duplicate, as-designed
