### ISSUE TITLE
Unable to specify output directory when using VSTest integration?

### ISSUE THREAD

**Issue by Stefanie899** [coverlet-coverage/coverlet#500] opened 2019-07-26 16:41 UTC
In the MSBuild integration of Coverlet, you can specify the output directory (and/or file) using -p:CoverletOutput='./result/'.

Am I correct that this feature is not available in the VSTest integration? And if so, are there any technical reasons why this can't be implemented into the VSTest integration?

**Comment by MarcoRossignoli** [comment] 2019-07-27 07:46
cc: @vagisha-nidhi

**Comment by MarcoRossignoli** [comment] 2019-08-14 08:57
cc @vagisha-nidhi @PBoraMSFT @cltshivash

**Comment by vagisha-nidhi** [comment] 2019-08-14 10:05
@MarcoRossignoli You can specify the results directory by using `dotnet test --results-directory:"e:\resDir"`. The coverage file will be by default generated in the results directory specified. This can be even given in the runsettings. 
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore21
https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019

**Comment by MarcoRossignoli** [comment] 2019-08-14 10:11
Great thanks for the answer!
@Stefanie899 can we close this?

**Comment by Stefanie899** [comment] 2019-08-14 17:57
@MarcoRossignoli that doesn't quite replicate the behavior of the MSBuild integration. The value I found in the original behavior is that you can specify the directory and that is the root directory where the coverage report will be output (this way it would just overwrite the same file, instead of creating a bunch of coverage reports)

In this case, using `... --results-directory:"./Path/"` it still creates a folder in the specified directory with a GUID, meaning you won't be able to overwrite coverage each time it is run, instead you get a new file each time.

**Comment by MarcoRossignoli** [comment] 2019-08-19 09:08
@vagisha-nidhi I think that GUID it's by design and it's not removable...right?

**Comment by MarcoRossignoli** [comment] 2019-09-16 08:31
ping @vagisha-nidhi

**Comment by vagisha-nidhi** [comment] 2019-09-16 11:07
@MarcoRossignoli yes, the GUID is by design and its not removable.

**Comment by MarcoRossignoli** [comment] 2019-09-16 11:19
@Stefanie899 I'm going to close after Vagisha's confirmation, this is non something that coverlet can solve, maybe a try on vstest repo.

**Comment by DaleyKD** [comment] 2020-03-27 20:38
Could you explain why that's not "removable?"  You have a constructor that takes that directory as a parameter, and in your default ctor, you use Guid.NewGuid().ToString().

While I understand you can't perfectly replicate the behavior of the .MSBuild, why not check to see if a property has been set in the .runsettings for the outputSubDirectory, and let it be **something static**.  Not having any idea what the output directory is going to be makes finding it a little difficult as part of a build process.

Even if it's just the ability to make it "/coverage" so that I know exactly where the .xml file will be would fix my issue.

**Comment by MarcoRossignoli** [comment] 2020-03-27 20:45
@DaleyKD I think that the right place to ask for this is  vstest repo https://github.com/microsoft/vstest/issues

**Comment by DaleyKD** [comment] 2020-03-27 20:53
@MarcoRossignoli : Please forgive me, I'm not trying to be obtuse.

Why can't you just use the other constructor for `AttachmentManager` here in `CoverletCoverageCollector` and pass in a setting (you'll have to create it) that you get from `RunSettings`?
![image](https://user-images.githubusercontent.com/7206282/77799537-08253f80-7043-11ea-842f-c85fe207843d.png)
My proposed solution has nothing (that *I* can see) to do with VSTest.

**Comment by MarcoRossignoli** [comment] 2020-03-27 20:58
That guid is added by vstest platform, that class is only a wrapper that send file to vstest platform, is vstest platform that write file and log to console file path. We have to follow vstest collector "protocol" otherwise future update on vstest platform could conflict with our custom behavior.

**Comment by MarcoRossignoli** [comment] 2020-03-27 21:11
> and pass in reportDirectoryName.

That class doesn't persist file...send only report stream to vstest plat through sink. This is the specs to implement a correct collector. This collector was written as by MS vstest team not by us. 

Why not simply update CI and move file where you want at the end of coverage test?

**Comment by MarcoRossignoli** [comment] 2020-03-28 08:00
@DaleyKD this is the place inside vstest where that guid is added to final path 

https://github.com/microsoft/vstest/blob/master/src/Microsoft.TestPlatform.Common/DataCollection/DataCollectionAttachmentManager.cs#L101-L125

That guid is always added at the end.

**Comment by Bertk** [comment] 2024-08-31 07:30
Coverlet CI is using properties in Directory.Build.props  for test results output directory.

https://github.com/coverlet-coverage/coverlet/blob/cf40840873588e3b596eebc25362732728b3d651/Directory.Build.props#L36C1-L44C19

**Closed by Bertk** 2024-08-31 07:30 UTC
Labels: tracking-external-issue, feature-request, driver-collectors
