### ISSUE TITLE
Incorrect branch coverage with await using

### ISSUE THREAD

**Issue by itsurkan** [coverlet-coverage/coverlet#914] opened 2020-07-29 12:04 UTC
If use 'using' statement only branch coverate is 100%
![image](https://user-images.githubusercontent.com/6732323/88797872-af121780-d1ac-11ea-9c1e-4aef9332187f.png)

If use 'await using' branch coverage is 50%
![image](https://user-images.githubusercontent.com/6732323/88797975-d10b9a00-d1ac-11ea-9467-d81724a099c4.png)
But they should be the same

**Comment by MarcoRossignoli** [comment] 2020-08-05 14:23
Which version are you using?

**Comment by alexthornton1** [comment] 2020-09-12 21:52
Out of curiosity, I checked whether my attempted fix of #907 would also address this.  It appears the answer to that is "no".  I started with this example:

```
public class AwaitUsing
{
    async public ValueTask AsyncAwait()
    {
        await using (var ms = new MemoryStream(System.Text.Encoding.ASCII.GetBytes("abc")))
        {
        }
    }
}
```

I tried this test (similar to what I added in #907, according to patterns of what was already there):

```
[Fact]
public void GetBranchPoints_IgnoresBranchesIn_AwaitUsing()
{
    // arrange
    var nestedName = typeof(AwaitUsing).GetNestedTypes(BindingFlags.NonPublic).First().Name;
    var type = _module.Types.FirstOrDefault(x => x.FullName == typeof(AwaitUsing).FullName);
    var nestedType = type.NestedTypes.FirstOrDefault(x => x.FullName.EndsWith(nestedName));
    var method = nestedType.Methods.First(x => x.FullName.EndsWith("::MoveNext()"));

    // act
    var points = _cecilSymbolHelper.GetBranchPoints(method);

    // assert
    Assert.Empty(points);
}
```

Without my #907 fix, there were eight branch points found.  With my #907 fix, there were six branch points found.

So, at the very least, we know these are separate issues.  Whether I'll be able to figure out what the issue _is_, well, that's a different story, but I'm just finding my way around this code base for the first time.

**Comment by alexthornton1** [comment] 2020-09-13 00:03
I took a crack at this one today, too.  The #914 fix depends on the #907 fix, but I'll create a separate pull request for the #914 fix.  (I can close the pull request for #907 and combine them into one, if you prefer.)

**Comment by alexthornton1** [comment] 2020-09-13 00:11
Working in Debug mode, but not Release mode.  Live and learn!  I'll investigate.

**Comment by alexthornton1** [comment] 2020-09-13 02:30
Fixed (I hope!) in 61e0d9f.

**Comment by Pankraty** [comment] 2020-09-24 15:54
We have the same issue and I've prepared a simple repro. Hope it will be useful

```
    public class TestClass
    {
        public async Task Example1()
        {
            await using var trans = new MyTransaction();
        }
        
        public async Task Example2()
        {
            var trans = new MyTransaction();
            await trans.DisposeAsync();
        }
    }
    
    public class MyTransaction : IAsyncDisposable
    {
        public async ValueTask DisposeAsync()
        {
        }
    }

    public class UnitTest1
    {
        [Fact]
        public async Task Test1()
        {
            var c = new TestClass();
            await c.Example1().ConfigureAwait(false);
        }

        [Fact]
        public async Task Test2()
        {
            var c = new TestClass();
            await c.Example2().ConfigureAwait(false);
        }
    }
```
**Expected behavior:** treat TestClass as having 100% test coverage both by lines and by conditions.

**Current behavior:** 
This line has 5 out of 10 branches covered:
```
            await using var trans = new MyTransaction();
```

This line has 1 of 2 branches covered:
```
            await trans.DisposeAsync();
```

----
The command line I use is
```
dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=./TestResults/
```

Target framework is netcoreapp3.1
Coverlet.MsBuild version is 2.9.0

The coverage report is attached.
[coverage.opencover.xml.log](https://github.com/coverlet-coverage/coverlet/files/5277396/coverage.opencover.xml.log)

**Comment by MarcoRossignoli** [comment] 2020-09-25 08:23
Thanks for the repro

**Comment by Totot0** [comment] 2020-11-01 15:41
Hello,

I have the same problem with testing a await method. Sonar tells me that the method is partially covered.
I am using coverlet.collector version 1.2.0
When this is resolved

**Comment by PovilasAtPoq** [comment] 2020-12-18 10:11
Any forecast when could this be fixed?

I've just literally stumbled upon same issue, that using `await using` creates multiple branches, and google brought me here :)

**Comment by msallin** [comment] 2021-03-02 17:06
Find Repros for #1104 #1103 #914 here: https://github.com/meggima/coverlet-reproductions

**Comment by MarcoRossignoli** [comment] 2021-03-08 07:37
closed in https://github.com/coverlet-coverage/coverlet/pull/1111

**Closed by MarcoRossignoli** 2021-03-08 07:37 UTC
Labels: bug, tenet-coverage, with repro

**Comment by rodchenkov** [comment] 2022-11-01 13:21
Sorry have the same issue now, can someone suggest how to fix?
Source code is here: https://github.com/GodelTech/GodelTech.Messaging.AzureServiceBus
Changes: https://github.com/GodelTech/GodelTech.Messaging.AzureServiceBus/pull/13
SonarCloud: https://sonarcloud.io/component_measures?metric=new_coverage&selected=GodelTech_GodelTech.Messaging.AzureServiceBus%3Asrc%2FGodelTech.Messaging.AzureServiceBus%2FAzureServiceBusSender.cs&view=list&pullRequest=13&id=GodelTech_GodelTech.Messaging.AzureServiceBus

**Comment by mu88** [comment] 2022-12-12 15:25
I can confirm @rodchenkov 's observation - I'm running into the same issue. I'm happy to provide a repro case if you need it - just let me know

**Comment by mu88** [comment] 2023-02-16 09:36
Any news about this, @MarcoRossignoli ?

**Comment by MarcoRossignoli** [comment] 2023-02-16 09:38
At the moment I don't have time to investigate this issue, if someone wants to take it would be good.
Also it would be good open another issue because the outcome issue is the same as this one but most likely the reason is different, like a different emitted IL by Roslyn for some new scenario.

**Comment by mu88** [comment] 2023-02-16 09:44
@rodchenkov could you create a new issue referencing your code?

**Comment by mu88** [comment] 2023-02-16 14:33
I've created the following issue: https://github.com/coverlet-coverage/coverlet/issues/1448

**Comment by mu88** [comment] 2023-02-16 16:41
@MarcoRossignoli whom should we ping? Or will somebody grab the new issue on its own?

**Comment by MarcoRossignoli** [comment] 2023-02-16 16:44
Coverlet is open source and we're not a lot as main developer, me and @daveMueller are the main contributors, at the moment I'm pretty buried and I don't have time, so if someone from the community wants to pick it up would be good, otherwise we don't have "fixed ETA" for updates.

**Comment by mu88** [comment] 2023-02-16 16:45
Thank you for your efforts - we do truly appreciate it!
