### ISSUE TITLE
Branch coverage always 100% although nothing was covered

### ISSUE THREAD

**Issue by huydq131** [coverlet-coverage/coverlet#1384] opened 2022-09-28 03:52 UTC
I'm using **coverlet.msbuild** on Azurepipeline and local machine for my very new project. The summary result are show 0% for branch coverage (that's correct) but when go throw the details of each class, I saw it show 100% always.
I'm not sure it's a bug or why the details are showing like that. Anyone please help to explain why it's showing differently?

**Comment by petli** [comment] 2022-09-28 06:20
There was a discussion about this in #1268, but it was closed as it petered out.

**Comment by huydq131** [comment] 2022-09-28 06:47
@MarcoRossignoli could please help on this one.

**Comment by MarcoRossignoli** [comment] 2022-09-28 07:00
Yep @petli is right coverlet is applying that accounting.

**Comment by huydq131** [comment] 2022-09-28 07:05
Thanks for your response @MarcoRossignoli, @petli,
I see your explanation in the #1268 and I think it make sense to show 100% for the case of no branch, that's great.
But in the summary it still show 0%, please see my image in the top. I think it should be summarize of all methods. Please correct me if I'm wrong.

**Comment by MarcoRossignoli** [comment] 2022-09-28 07:19
What's reporter are you using? If you look at the report generated(I suppose cobertura) does the numbers make sense? I mean I don't understand if the problem is of reported or inside the generated report.

**Comment by huydq131** [comment] 2022-09-28 07:32
@MarcoRossignoli , 
Yes I run the coverlet and get the result is coverage.cobertura.xml, then I use the ReportGenerator to convert it.

**Comment by MarcoRossignoli** [comment] 2022-09-28 07:34
Ok but the values inside cobertura match the report?

**Comment by huydq131** [comment] 2022-09-28 08:16
@MarcoRossignoli,
I've check, the values come from coverage.cobertura.xml, it's not by ReportGenerator tool.

**Comment by MarcoRossignoli** [comment] 2022-09-28 08:20
If I recall well in cobertura there's no summarization, isn't a report behavior? 100% on method column is because that method doesn't have branch and so are 100% covered. I mean that two values should be taken by different perspective and not been put together.

**Comment by huydq131** [comment] 2022-09-28 08:40
Enough information for me. Thank you so much @MarcoRossignoli.

**Closed** 2022-09-28 08:46 UTC
Labels: as-designed

**Comment by MarcoRossignoli** [comment] 2022-09-28 08:58
You're welcome
