### ISSUE TITLE
Question about switch expression with ?? operator

### ISSUE THREAD

**Issue by sungam3r** [coverlet-coverage/coverlet#1292] opened 2022-02-06 12:15 UTC
See https://app.codecov.io/gh/graphql-dotnet/parser/blob/master/src/GraphQLParser/ParserContext.Parse.cs
All 4 usages of `ExpectOneOf` (lines 862, 1101, 1114, 1353) are partilly covered though there are tests that call `ExpectOneOf` with null and non-null values. Why so?

**Comment by daveMueller** [comment] 2022-02-07 00:42
We have to look into it, could be a bug. Thanks for reporting this.

It's related to null-coalescing operator inside method argument.

![grafik](https://user-images.githubusercontent.com/19378678/152708883-cd646e38-46a6-4fa6-9110-594f2a19970f.png)

**Comment by daveMueller** [comment] 2022-02-09 23:14
I took a quick peek and it really seems to be a bug. I created a simplified repro here: [https://github.com/daveMueller/CoverletIssue1292](https://github.com/daveMueller/CoverletIssue1292) and I will start working on this.

**Comment by daveMueller** [comment] 2022-02-10 00:24
OK seems to be a really special case. When I change the default value to just `underscore` coverage works.

![grafik](https://user-images.githubusercontent.com/19378678/153313189-293e221b-49d9-4f70-a5f9-fdc1db8962ef.png)

**Comment by sungam3r** [comment] 2022-02-10 07:59
What if you try `string?`?

**Comment by daveMueller** [comment] 2022-02-10 12:31
Thanks, but it's the same with `string?`. This is getting way more complicated than I thought it would be 😄. For switch cases the compiler generates multiple branch point. Depending on how complex the switch expression is the amount of those generated branch points can vary. In the simplest form the issue here looks like this (not related to `??` at all):

![grafik](https://user-images.githubusercontent.com/19378678/153407532-39de3877-cc35-4734-895b-6022bf88abbb.png)

I suspect the second branch is generated as the `else` branch to the default case. If the switch expression doesn't have a defined default case, the compiler generates an exception.

![grafik](https://user-images.githubusercontent.com/19378678/153408331-9f81d276-0377-4b48-96d3-bbba7b69661b.png)

Nevertheless I have to look into which of the generated branch point we already exclude and which have to be excluded in addition.

**Comment by sungam3r** [comment] 2022-02-10 16:41
So actually it may be a question to Roslyn team.

**Comment by daveMueller** [comment] 2022-02-11 01:12
Yes I also started to think that this most likely isn't an issue with coverlet. Because you can fully cover the code when you know that it can throw an exception. E.g. the function
```
public static bool DoSomething(string? foo)
{
   return foo switch
   {
      "hello" => true
   };
}
```
Can be fully covered with
```
[Fact]
public void Test1()
{
   Assert.True(Class1.DoSomething("hello"));
   Assert.Throws<SwitchExpressionException>(() => Class1.DoSomething(""));
}
```

![grafik](https://user-images.githubusercontent.com/19378678/153521077-86d4e875-78fd-481a-a9a4-36fd68580dad.png)

When I looked into your code I also thought you handled all the bad cases up front (e.g. with ??) and thats why there is no warning anymore. So I also don't really understand why the compiler still generates the exception. Maybe this really is a Roslyn issue.

Nevertheless I don't think that coverlet has an issue here anymore.

**Comment by sungam3r** [comment] 2022-02-11 15:42
There was no case for null in my switch.

**Comment by daveMueller** [comment] 2022-02-12 02:53
Yes you are right.

**Comment by daveMueller** [comment] 2022-03-09 00:31
Closing this because coverlet works as designed. Feel free to reopen.

**Closed by daveMueller** 2022-03-09 00:31 UTC
Labels: bug
