### ISSUE TITLE
DeterministicBuild workaround doc version misleading

### ISSUE THREAD

**Issue by Confuzed** [coverlet-coverage/coverlet#1008] opened 2020-12-06 12:50 UTC
## The Problem

I have been trying to work out why my coverage reports were empty when my project is built by GitHub actions. Searching the issues and doc's here I did find the information about the Deterministic workaround ([here](https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/DeterministicBuild.md)). Initially I dismissed the workaround because it states in the title **'only for .NET Core SDK < 3.1.100'**. My project is using SDK 3.1.404. When I couldn't find any other hints I decided to try the workaround anyway, and that does in fact fix the issue.

## More Information

Interestingy, the issue only seems to present itself when I add SourceLink support to the project being tested, regardless of the presence of the _ContinuousIntegrationBuild_ property in the project.

I have a repository where I did my testing for this, which you're welcome to check. You'll see that I was making changes in steps to make the project closer to that of my "real" project until I found where the coverage report became empty. Then I added the branch 'deterministic-workaround' to test the workaround. You can see the results in the Actions tab.

* [The test repository](https://github.com/Confuzed/CoverageTest)
* [Actions results](https://github.com/Confuzed/CoverageTest/actions)
* [Workaround branch](https://github.com/Confuzed/CoverageTest/compare/deterministic-workaround)

## Suggested Solution

In the short-term, update the documentation to make it clear that the workaround does apply to 3.1.404, at least if SourceLink is present. I don't know whether there is also a code-fix that can be made later.

**Comment by MarcoRossignoli** [comment] 2020-12-12 16:51
The issue is that documentation reflect master version, at the moment deterministic workaround is needed for version < 3.1.00 and also there was a bug, fixed on master.

https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/Changelog.md#fixed

Take a look at fixed and added section

**Comment by tonyhallett** [comment] 2020-12-12 17:10
@MarcoRossignoli when are you releasing v3 proposed for 1/7 ?  It is misleading/confusing when the docs mention features that are only present in nightly.

**Comment by MarcoRossignoli** [comment] 2020-12-12 17:32
> It is misleading/confusing when the docs mention features that are only present in nightly.

I apologize, you're right, past months were a bit chaotic for me and I hadn't enough time to take care of coverlet. Sorry, sometimes OSS has got this kind of problem.
Anyway, I'd like to push new version to official before end of year, I'd like to understand if I can fix also https://github.com/coverlet-coverage/coverlet/issues/992 before that deadline because is a new feature used a lot today.

Pls feel free to use my tmp for now.

@tonerdo do you have some ETA for nightly fix?

**Comment by Confuzed** [comment] 2020-12-12 17:49
@MarcoRossignoli Obviously the view that consumers will have of the repository is the head of the default branch, so its better when that reflects the latest release rather than the "in development" version. A frustrating situation, but common on GitHub! 🙄 

Thank you for the feedback. I'll leave my workaround in place until the next release is available. You can close this issue if you don't intend to use it to track any changes or discussion. 👍

**Comment by MarcoRossignoli** [comment] 2020-12-12 17:59
>  A frustrating situation, but common on GitHub! 🙄

Yep I know, here we were a bit late with the planning so it's our fault. Usually we release after big updates/fix so documentation is not out of synch for much time.

I'll close this for now because I don't have fix to do and I prefer keep backlog clean. 

Thanks a lot for your advice and sorry for the "frustration", but thanks for use coverlet!

**Closed by MarcoRossignoli** 2020-12-12 17:59 UTC
Labels: Solved, as-designed
