### ISSUE TITLE
Lower covered lines after using coverlet 3.0.0

### ISSUE THREAD

**Issue by marceloodiniz** [coverlet-coverage/coverlet#1049] opened 2021-01-14 11:48 UTC
Hi, I was using "coverlet.collector" version 1.3.0 and changed to 3.0.0. My coverage changed from 70% to 50%. Comparing the results, it seams that this new version have some problem detecting that a line was visited. My "uncovered lines" was 651 and changed to 1239 on this new version.

Analyzing one of the files that increased de uncovered lines, I saw many lines that my unit test covers but the report shows 0 visits.

Version 1.3.0
![image](https://user-images.githubusercontent.com/6569081/104586421-34e32b80-5644-11eb-8941-bb5e0a507ed7.png)
 
Version 3.0.0
![image](https://user-images.githubusercontent.com/6569081/104586475-462c3800-5644-11eb-973f-fac5ac9c2d29.png)

**Comment by Malivil** [comment] 2021-01-14 12:30
Duplicate of #1043, fixed in nightly and next release

**Comment by marceloodiniz** [comment] 2021-01-14 12:51
Thanks @Malivil, but I referenced the nightly build version on my project (version 3.0.1-preview.2.gd43f83d824) and it has the same problem!

**Comment by Malivil** [comment] 2021-01-14 13:02
I may have misspoke about it being available on nightly already. @MarcoRossignoli says in #1037 that it will be available in the next nightly which might not build until tonight.

You can try the local preview that @daveMueller did here: https://github.com/coverlet-coverage/coverlet/issues/1037#issuecomment-759232073

**Comment by marceloodiniz** [comment] 2021-01-14 13:23
@Malivil, this local version solved my problem :) 
When will version 3.0.1 be released?

3.0.1-preview.4
![image](https://user-images.githubusercontent.com/6569081/104596113-5519e700-5652-11eb-9806-0a8d098988f6.png)

**Comment by Malivil** [comment] 2021-01-14 13:59
In #1037 @MarcoRossignoli says he'll release it ASAP but he's a bit busy so we'll just have to wait it out

**Closed** 2021-01-14 14:15 UTC
