### ISSUE TITLE
Include in the documentation how to uninstall coverlet

### ISSUE THREAD

**Issue by JoeMarkov** [coverlet-coverage/coverlet#1005] opened 2020-11-27 12:43 UTC
I am not able to find how to uninstall coverlet from my system and from my default test templates.

Coverlet does not show up here:

dotnet tool list -g
dotnet tool list

I wish the documentation in the readme.md included this information

**Comment by MarcoRossignoli** [comment] 2020-11-27 14:02
We linked .NET tools guide on readme https://github.com/coverlet-coverage/coverlet#net-global-tool-guide-suffers-of-possible-known-issue if you got to official MS guide you can see standard uninstall command https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#uninstall-a-tool

**Comment by tonerdo** [comment] 2020-12-15 17:24
@JoeMarkov, in addition, you'd have to look at Microsoft documentation to figure out how to remove (if possible) Coverlet from the default test templates

**Comment by MarcoRossignoli** [comment] 2020-12-15 17:38
I don't think it's possible remove coverlet from default .NETCore xunit test template cc: @nohwnd

**Comment by JoeMarkov** [comment] 2020-12-16 10:33
oh, its part of the official test template? Perhaps that why I was confused why it was added to my projects and why I wanted to remove it. I though the installer of coverlet injected itself into my standard xunit templates....

**Comment by MarcoRossignoli** [comment] 2020-12-20 14:39
@JoeMarkov I confirm that coverlet is injected by design to xunit template project.

I'm going to close this as-designed.

Feel free to reopen if needed.

**Closed by MarcoRossignoli** 2020-12-20 14:39 UTC
Labels: as-designed, documentation, question
